version: "3.4"

services:
  app:
    build:
      context: .
      args:
        ENV: dev
      target: app
    command: sh -c "mix deps.get && mix ecto.migrate && mix seed && mix phx.server"
    depends_on:
      - db
      - sync
    volumes:
     - ./keys.d/:/keys.d
    environment:
      DATABASE_URL: "psql://kniffel:kniffel@db/kniffel"
      PRIV_KEY_PATH: "/keys.d/server.key"
      AES_KEY: "dev"
      URL: "http://hoge.cloud:3000"
      MASTER_URL: "http://hoge.cloud:3000"
      SECRET_KEY_BASE: vmOZLCImcoi+PBCMC/N6BnQ8t6LmSRyONqK3T0iNSV9hx2pt7502lV2mN2alVAFe
    ports:
      - "4000:4000"

  assets:
    build:
      context: .
      target: assets
      args:
        ENV: dev
    depends_on:
      - sync
    ports:
      - "4001:4001"
    command: sh -c "yarn install && yarn run watch"

  db:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_USER: kniffel
      POSTGRES_PASSWORD: kniffel
      POSTGRES_DB: kniffel
    ports:
      - "15432:5432"
