version: "3.4"

services:
  app:
    build:
      context: .
      args:
        ENV: test
      target: app
    command: sh -c "mix deps.get && mix test.watch --exclude load"
    depends_on:
      - db
      - sync
    volumes:
      - ./kniffel.key:/kniffel.key
    environment:
      DATABASE_URL: "psql://kniffel_test:kniffel@db/kniffel_test"
      PRIV_KEY_PATH: "/kniffel.key"
      AES_KEY: "dev"
      URL: "http://hoge.cloud:3000"
      MASTER_URL: "https://kniffel.app"

  assets:
    build:
      context: .
      target: assets
      args:
        ENV: test
    depends_on:
      - sync
    command: sh -c "yarn install && yarn run watch"


  db:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_USER: kniffel_test
      POSTGRES_PASSWORD: kniffel
      POSTGRES_DB: kniffel_test
