name: publish-image
on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
    - name: login-github-packages
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: "docker.pkg.github.com"
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY_URL
    - name: checkout-repo
      uses: actions/checkout@master
    - name: build-image
      run: docker build --pull -t docker.pkg.github.com/tbho/kniffel/kniffel .
    - name: update-wiwi-gitlab
      if: github.ref == 'refs/heads/master'
      run: |
        git fetch --unshallow origin
        git remote add GitLab https://t_hoge03:$GITLAB_PAT@wiwi-gitlab.uni-muenster.de/bachelor-thesis-tobias-hoge/kniffel.git
        git push GitLab
      env:
        GITLAB_PAT: ${{ secrets.GITLAB_PAT }}
    - name: push-image-master
      run: docker push docker.pkg.github.com/tbho/kniffel/kniffel
      if: github.ref == 'refs/heads/master'
